Repository Mirazyzz/ExpenseTracker, pull requests merged in 2024-11, with the labels that each got.

#73 Notification Store updates
  ExpenseTracker/ExpenceTracker.Domain/Entities/Notification.cs
  ExpenseTracker/ExpenseTracker.Application/Services/Interfaces/INotificationUrlService.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/Interfaces/INotificationStore.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/NotificationStore.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/WalletStore.cs
  ExpenseTracker/ExpenseTracker.Infrastructure/Repositories/NotificationRepository.cs
  ExpenseTracker/ExpenseTracker.Infrastructure/Repositories/WalletRepository.cs
  ExpenseTracker/ExpenseTracker/Controllers/WalletsController.cs
  ExpenseTracker/ExpenseTracker/Views/Shared/_Layout.cshtml
Labels: enhancement

#80 Fix notificatins URL
  ExpenseTracker/ExpenseTracker/Views/Shared/_Layout.cshtml
Labels: bug

#81 all of index pages made responsive
  ExpenseTracker/ExpenseTracker/Views/Categories/Index.cshtml
  ExpenseTracker/ExpenseTracker/Views/Shared/_Sidebar.cshtml
  ExpenseTracker/ExpenseTracker/Views/Transfers/Index.cshtml
  ExpenseTracker/ExpenseTracker/Views/Wallets/Index.cshtml
  ExpenseTracker/ExpenseTracker/wwwroot/css/site.css
Labels: bug

#91 Fixed-the-transfer-create-window
  ExpenseTracker/ExpenseTracker/Views/Transfers/Create.cshtml
  ExpenseTracker/ExpenseTracker/Views/Transfers/Edit.cshtml
  ExpenseTracker/ExpenseTracker/Views/Transfers/Index.cshtml
Labels: bug

#88 sidebar has been made responsive
  ExpenseTracker/ExpenseTracker/Views/Shared/_Sidebar.cshtml
  ExpenseTracker/ExpenseTracker/wwwroot/css/site.css
Labels: enhancement

#87 Update database setup instructions to README
  README.md
Labels: invalid

#86 Refactor UserRequestID to UserRequest, rename user to ApplicationUser…
  ExpenseTracker/ExpenseTracker.Application/Mappings/UserMappings.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/ApplicationUser/UpdateApplicationUserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Category/CategoryRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Category/CreateCategoryRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Category/GetCategoriesRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Common/UserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Notification/GetNotificationsRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Transfer/CreateTransferRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Transfer/GetTransfersRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Transfer/TransferRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/User/CreateUserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/User/GetUserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/User/UpdateUserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/User/UserRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Wallet/CreateWalletRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Wallet/GetWalletsRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/Wallet/WalletRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/WalletShare/CreateWalletShareRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/WalletShare/GetWalletSharesRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Requests/WalletShare/WalletShareRequest.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/Interfaces/INotificationStore.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/Interfaces/IUserStore.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/NotificationStore.cs
  ExpenseTracker/ExpenseTracker.Application/Stores/UserStore.cs
  ExpenseTracker/ExpenseTracker.Application/ViewModels/ApplicationUser/ApplicationUserViewModel.cs
  ExpenseTracker/ExpenseTracker/Controllers/TransfersController.cs
  ExpenseTracker/ExpenseTracker/Controllers/WalletsController.cs
  ExpenseTracker/ExpenseTracker/Filters/UserRequestFilter.cs
Labels: duplicate, invalid
